# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perm',
            field=models.IntegerField(default=0),
        ),
    ]
