# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180326_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('perm_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='permission',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='perm_id',
        ),
    ]
